// Generated by CoffeeScript 1.3.3
(function() {
  var socket;

  socket = io.connect('http://app.planning.tunk.io', {
    port: 3000
  });

  socket.on('participants', function(count) {
    var _results;
    if ($('#participants .icon-user').size() === count) {
      return;
    }
    $('#participants .icon-user').remove();
    _results = [];
    while (count-- > 0) {
      _results.push($('#participants').append('<i class="icon-user"></i> ').hide().fadeIn());
    }
    return _results;
  });

  $('#card').on('click', function(e) {
    return socket.emit('ready', true);
  });

  socket.on('ready', function(ready) {
    if (ready) {
      return alert('READY');
    }
  });

}).call(this);
